permissions:
  contents: write
  id-token: write
on:
  workflow_dispatch:
  pull_request:
    paths:
      - 'backend.tf'
      - 'ghidra-server.tf'
jobs:
  tofu-plan:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v4
    - name: Configure AWS Credentials
      uses: aws-actions/configure-aws-credentials@v4
      with:
        role-to-assume: ${{ secrets.AWS_ROLE_ARN }}
        aws-region: us-east-2
    - uses: opentofu/setup-opentofu@v1
      with:
        tofu_version: 1.6.2
    - name: "Tofu Plan"
      run: |
        tofu init
        tofu plan
